import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";

const suse = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DBly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${suse.className} antialiased dark`}>
        <main className="container min-h-screen">
          <Nav />
          <div className="mt-5">{children}</div>
        </main>
      </body>
    </html>
  );
}
