import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import { ThemeProvider } from "@/components/theme-provider";

const suse = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ZenDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${suse.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="container min-h-screen">
            <Nav />
            <div className="mt-5">{children}</div>
          </main>{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
